# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Configuration file for the Access Activity Model (VMRay sandbox)

# --------------------------------------------
# Filesystem
# --------------------------------------------
filesystem:
# Kernel system calls for filesystem
  - api_call_name: "^(Nt|Zw)CreateFile$"
    handle_returned_in: "FileHandle"
    path_param: "ObjectAttributes:ObjectName"
    handle_is_out: True
    operation: "create"
  - api_call_name: "NtCreatePagingFile$"
    path_param: "PageFileName"
    operation: "write"
  - api_call_name: "^(Nt|Zw)DeleteFile$"
    path_param: "ObjectAttributes:ObjectName"
    operation: "delete"
  - api_call_name: "^(Nt|Zw)FlushBuffersFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)LockFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)UnlockFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)OpenFile$"
    handle_returned_in: "FileHandle"
    handle_is_out: True
    path_param: "ObjectAttributes:ObjectName"
    operation: "read"
  - api_call_name: "^(Nt|Zw)OpenProcess$"
    path_param: "ObjectAttributes:ObjectName"
    operation: "execute"
  - api_call_name: "^(Nt|Zw)QueryAttributesFile$"
    path_param: "ObjectAttributes:ObjectName"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryDirectoryFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryEaFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryAttributesFile$"
    path_param: "ObjectAttributes:ObjectName"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryFullAttributesFile$"
    path_param: "ObjectAttributes:ObjectName"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryInformationFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryInformationFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryQuotaInformationFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryVolumeInformationFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)ReadFile$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)ReadFileScatter$"
    handle_param: "FileHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)SetEaFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)SetInformationFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)SetQuotaInformationFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)SetVolumeInformationFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)WriteFile$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)WriteFileGather$"
    handle_param: "FileHandle"
    operation: "write"
  - api_call_name: "LdrLoadDll"
    path_param: "Name"
    operation: "execute"
  - api_call_name: "^LoadLibrary(Ex|)[AW]$"
    path_param: "lpLibFileName"
    handle_returned_in: "return"
    operation: "execute"
# Userland API calls for filesystem
  - api_call_name: "^CreateFile[AW]$"
    handle_returned_in: "return"
    path_param: "lpFileName"
    operation: "create"
  - api_call_name: "fopen"
    handle_returned_in: "return"
    path_param: "_Filename"
    operation: "read"
  - api_call_name: "ReadFile"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "WriteFile"
    handle_param: "hFile"
    operation: "write"
  - api_call_name: "^CreateProcess[AW]$"
    path_param: "lpApplicationName"
    cmd_line_param: "lpCommandLine"
    operation: "execute"
  - api_call_name: "^CopyFile(Ex|)[AW]$"
    path_param: "lpExistingFileName"
    operation: "read"
  - api_call_name: "^CopyFile(Ex|)[AW]$"
    path_param: "lpNewFileName"
    operation: "create"
  - api_call_name: "^CreateFileMapping[AW]$"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "^DeleteFile[AW]$"
    path_param: "lpFileName"
    operation: "delete"
  - api_call_name: "FlushFileBuffers"
    handle_param: "hFile"
    operation: "write"
  - api_call_name: "^GetFileAttributes(Ex|)[AW]$"
    path_param: "lpFileName"
    operation: "read"
  - api_call_name: "^GetFileSize(Ex|)$"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "GetFileTime"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "GetFileType"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "^GetFileVersionInfo[AW]$"
    path_param: "lptstrFilename"
    operation: "read"
  - api_call_name: "^GetFileVersionInfoSize[AW]$"
    path_param: "lptstrFilename"
    operation: "read"
  - api_call_name: "^GetFileVersionInfoSizeEx[AW]$"
    path_param: "lpwstrFilename"
    operation: "read"
  - api_call_name: "^GetModuleFileName(Ex|)[AW]$"
    path_param: "lpFilename"
    path_param_is_out: True
    operation: "read"
  - api_call_name: "^GetMappedFileName[AW]$"
    path_param: "lpFilename"
    path_param_is_out: True
    operation: "read"
  - api_call_name: "^GetPrivateProfile(Int|String)[AW]$"
    path_param: "lpFilename"
    operation: "read"
  - api_call_name: "^GetPrivateProfileSection(Names|)[AW]$"
    path_param: "lpFilename"
    operation: "read"
  - api_call_name: "^GetTempFileName[AW]$"
    path_param: "lpTempFileName"
    path_param_is_out: True
    operation: "create"
  - api_call_name: "ICreateErrorInfo:SetHelpFile"
    path_param: "szHelpFile"
    operation: "read"
  - api_call_name: "ICreateTypeLib:SetHelpFileName"
    path_param: "szHelpFileName"
    operation: "read"
  - api_call_name: "IErrorInfo:GetHelpFile"
    path_param: "pBstrHelpFile"
    operation: "read"
  - api_call_name: "IoCreateFile"
    handle_returned_in: "FileHandle"
    handle_is_out: True
    path_param: "ObjectName"
    operation: "create"
  - api_call_name: "IFileOperation:CopyItem"
    handle_param: "psiItem"
    operation: "read"
  - api_call_name: "IFileOperation:CopyItem"
    handle_param: "psiDestinationFolder"
    file_name_param: "pszCopyName"
    operation: "create"
  - api_call_name: "^(Lock|Unlock)File(Ex|)$"
    handle_param: "hFile"
    operation: "read"
  - api_call_name: "SetEndOfFile"
    handle_param: "hFile"
    operation: "write"
  - api_call_name: "SetFileTime"
    handle_param: "hFile"
    operation: "write"
  - api_call_name: "^MoveFile(Ex|)[AW]$"
    path_param: "lpExistingFileName"
    operation: "delete"
  - api_call_name: "^MoveFile(Ex|)[AW]$"
    path_param: "lpNewFileName"
    operation: "create"
  - api_call_name: "^MoveFileWithProgress[AW]$"
    path_param: "lpExistingFileName"
    operation: "delete"
  - api_call_name: "^MoveFileWithProgress[AW]$"
    path_param: "lpNewFileName"
    operation: "create"
  - api_call_name: "NetFwAuthorizedApplication:INetFwAuthorizedApplication:put_ProcessImageFileName"
    path_param: "ProcessImageFileName"
    operation: "read"
  - api_call_name: "^PathFileExists[AW]$"
    path_param: "pszPath"
    operation: "read"
  - api_call_name: "^SetFile(Attributes|Security)[AW]?$"
    path_param: "lpFileName"
    operation: "write"
  - api_call_name: "SHCreateItemFromParsingName"
    handle_returned_in: "ppv"
    handle_is_out: True
    path_param: "pszPath"
    operation: "read"
  - api_call_name: "^ShellExecute(Ex|)[AW]$"
    path_param: "lpFile"
    operation: "execute"
  - api_call_name: "^SHFileOperation[AW]$"
    path_param: "pFrom"
    operation: "read"
  - api_call_name: "^SHFileOperation[AW]$"
    path_param: "pTo"
    operation: "create"
  - api_call_name: "^SHGetFileInfo[AW]$"
    path_param: "pszPath"
    operation: "read"
  - api_call_name: "^URLDownloadToFile[AW]$"
    path_param: "(szFileName|param_3)"
    operation: "create"
  - api_call_name: "^WritePrivateProfileString[AW]$"
    path_param: "lpFileName"
    operation: "write"

# --------------------------------------------
# Registry
# --------------------------------------------
registry:
# Kernel system calls for registry
  - api_call_name: "^(Nt|Zw)CreateKey(Transacted|)$"
    handle_param: "RootDirectory"
    handle_returned_in: "KeyHandle"
    handle_is_out: True
    path_param: "ObjectName"
    operation: "create"
  - api_call_name: "^(Nt|Zw)OpenKey(Transacted|)(Ex|)$"
    handle_param: "RootDirectory"
    handle_returned_in: "KeyHandle"
    handle_is_out: True
    path_param: "ObjectName"
    operation: "read"
  - api_call_name: "^(Nt|Zw)DeleteKey$"
    handle_param: "KeyHandle"
    operation: "delete"
  - api_call_name: "^(Nt|Zw)DeleteValueKey$"
    handle_param: "KeyHandle"
    path_param: "ValueName"
    operation: "delete"
  - api_call_name: "^(Nt|Zw)QueryKey$"
    handle_param: "KeyHandle"
    path_param: "KeyInformationClass:KeyNameInformation:Name"
    operation: "read"
  - api_call_name: "^(Nt|Zw)QueryKeyValue$"
    handle_param: "KeyHandle"
    path_param: "KeyValueInformationClass:KeyValueBasicInformation:Name"
    operation: "read"
  - api_call_name: "^(Nt|Zw)EnumerateKey$"
    handle_param: "KeyHandle"
    path_param: "KeyInformationClass:KeyNameInformation:Name"
    operation: "read"
  - api_call_name: "^(Nt|Zw)EnumerateValueKey"
    handle_param: "KeyHandle"
    operation: "read"
  - api_call_name: "^(Nt|Zw)FlushKey"
    handle_param: "KeyHandle"
    operation: "write"
  - api_call_name: "^(Nt|Zw)SetValueKey$"
    handle_param: "KeyHandle"
    path_param: "ValueName"
    operation: "write"
# Userland API calls for registry
  - api_call_name: "^RegCreateKey(Ex|)[AW]$"
    handle_param: "hKey"
    handle_returned_in: "phkResult"
    path_param: "lpSubKey"
    operation: "create"
    handle_is_out: True
  - api_call_name: "^RegOpenKey(Ex|)[AW]$"
    handle_param: "hKey"
    handle_returned_in: "phkResult"
    path_param: "lpSubKey"
    operation: "read"
    handle_is_out: True
  - api_call_name: "^RegDeleteKey(Ex|)[AW]$"
    handle_param: "hKey"
    path_param: "lpSubKey"
    operation: "delete"
  - api_call_name: "^RegDeleteValue(Ex|)[AW]$"
    handle_param: "hKey"
    path_param: "lpValueName"
    operation: "delete"
  - api_call_name: "^RegEnumKey(Ex|)[AW]$"
    handle_param: "hKey"
    path_param: "lpName"
    path_param_is_out: True
    operation: "read"
  - api_call_name: "^RegEnumValue(Ex|)[AW]$"
    handle_param: "hKey"
    path_param: "lpValueName"
    path_param_is_out: True
    operation: "read"
  - api_call_name: "RegFlushKey"
    handle_param: "hKey"
    operation: "write"
  - api_call_name: "^RegGetValue[AW]$"
    handle_param: "hKey"
    path_param: "lpSubKey"
    value_param: "lpValue"
    operation: "read"
  - api_call_name: "RegNotifyChangeKeyValue"
    handle_param: "hKey"
    operation: "read"
  - api_call_name: "^RegQueryInfoKey[AW]$"
    handle_param: "hKey"
    operation: "read"
  - api_call_name: "^RegQueryValue(Ex|)[AW]$"
    handle_param: "hKey"
    path_param: "lpValueName"
    operation: "read"
  - api_call_name: "^RegSetValueEx[AW]$"
    handle_param: "hKey"
    path_param: "lpValueName"
    operation: "write"
  - api_call_name: "^RegSetValue[AW]$"
    handle_param: "hKey"
    path_param: "lpSubKey"
    operation: "write"
  - api_call_name: "RegOpenCurrentUser"
    handle_id: 0x80000001
    handle_returned_in: "phkResult"
    handle_is_out: True
    operation: "read"
# --------------------------------------------
# Network
# --------------------------------------------
network:
# Winsock2
  - api_call_name: "^(connect|WSAConnect)$"
    handle_returned_in: "s"
    host_param: "sin_addr"
    port_param: "sin_port"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^(recv|WSARecv)$"
    handle_param: "s"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^(recvfrom|WSARecvFrom)$"
    handle_param: "s"
    network_type: "listen"
    operation: "read"
  - api_call_name: "sendto"
    handle_param: "s"
    network_type: "listen"
    operation: "read"
  - api_call_name: "^(send|WSASend)$"
    handle_param: "s"
    network_type: "connect"
    operation: "write"
  - api_call_name: "gethostbyname"
    dns_name_param: "return:h_name"
    dns_ip_param: "return:h_addr_list"
    network_type: "dns"
  - api_call_name: "getaddrinfo"
    dns_name_param: "pNodeName"
    dns_ip_param: "ppResult:ai_addr:sin_addr"
    network_type: "dns"
  - api_call_name: "bind"
    handle_returned_in: "s"
    host_param: "sin_addr"
    port_param: "sin_port"
    network_type: "listen"
    operation: "create"
# Wininet
  - api_call_name: "^InternetConnect[AW]$"
    handle_returned_in: "return"
    host_param: "lpszServerName"
    port_param: "nServerPort"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^InternetOpenUrl[AW]$"
    handle_returned_in: "return"
    url_param: "lpszUrl"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^HttpOpenRequest[AW]$"
    handle_param: "hConnect"
    handle_returned_in: "return"
    request_param: "lpszObjectName"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^HttpQueryInfo[AW]$"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "read"
  - api_call_name: "^HttpSendRequest(Ex|)[AW]$"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "write"
  - api_call_name: "^HttpAddRequestHeaders[AW]$"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "write"
  - api_call_name: "InternetReadFile"
    handle_param: "hFile"
    network_type: "connect"
    operation: "read"
  - api_call_name: "InternetWriteFile"
    handle_param: "hFile"
    network_type: "connect"
    operation: "write"
# Winhttp
  - api_call_name: "WinHttpConnect"
    handle_returned_in: "return"
    host_param: "pswzServerName"
    port_param: "nServerPort"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpOpenRequest"
    handle_param: "hConnect"
    handle_returned_in: "return"
    request_param: "pwszObjectName"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpQueryDataAvailable"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpQueryHeaders"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpReadData"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpReceiveResponse"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "read"
  - api_call_name: "WinHttpSendRequest"
    handle_param: "hRequest"
    network_type: "connect"
    operation: "write"
# Urlmon
  - api_call_name: "^URLDownloadToFile[AW]$"
    url_param: "(szURL|param_2)"
    network_type: "connect"
    operation: "read"
  - api_call_name: "IInternetProtocolRoot:Start"
    handle_param: "This"
    url_param: "szURL"
    network_type: "connect"
    operation: "read"
  - api_call_name: "IInternetProtocolRoot:Start"
    handle_param: "This"
    url_param: "szURL"
    network_type: "connect"
    operation: "read"
  - api_call_name: "IInternetSession:CreateBinding"
    handle_returned_in: "ppOInetProt"
    url_param: "szURL"
    handle_is_out: True
    network_type: "connect"
    operation: "read"

# --------------------------------------------
# Handle Closing
# --------------------------------------------
close:
# Filesystem
  - api_call_name: "^(Nt|Zw)Close$"
    handle_param: "Handle"
  - api_call_name: "CloseHandle"
    handle_param: "hObject"
  - api_call_name: "fclose"
    handle_param: "_File"
  - api_call_name: "IUnknown:Release$"
    handle_param: "This"
# Registry
  - api_call_name: "RegCloseKey"
    handle_param: "hKey"
